
STUDIALIS_ENV=vagrant;
export STUDIALIS_ENV;

STUDIALIS_CLI=false;
export STUDIALIS_CLI;

STUDIALIS_CONTEXT=fo;
export STUDIALIS_CONTEXT;

STUDIALIS_INTERNAL_IP_MASK=10.41.111.[0-9]{1,3}\;192.168.[0-9]{1,3}.[0-9]{1,3}\;213.56.106.[0-9]{1,3}\;10.0.[0-9]{1,3}.[0-9]{1,3};
export STUDIALIS_INTERNAL_IP_MASK;

STUDIALIS_ATTACHMENT_SERVER_FO=dsi16.pl.oxymis.fr;
export STUDIALIS_ATTACHMENT_SERVER_FO;

STUDIALIS_ATTACHMENT_SERVER_BO=dsi17.pl.oxymis.fr;
export STUDIALIS_ATTACHMENT_SERVER_BO;

WS_SYNAPSE_HOST=http://rails.si.oxymis.fr/synapse/;
export WS_SYNAPSE_HOST;

WS_RAILS_HOST=http://rails.si.oxymis.fr/;
export WS_RAILS_HOST;


GLOBAL_DATA_HOST=mkt-mysql1.pl.oxymis.fr;
export WS_GLOBAL_DATA_HOST;

GLOBAL_BDD_PORT=3306;
export GLOBAL_BDD_PORT;

GLOBAL_DD_DRIVER=mysql;
export GLOBAL_DD_DRIVER;

GLOBAL_BDD_DATABASE=studialis_security;
export GLOBAL_BDD_DATABASE;

GLOBAL_BDD_TABLE=login_attempts;
export GLOBAL_BDD_TABLE;

GLOBAL_BDD_USER=StudSec;
export GLOBAL_BDD_USER;

GLOBAL_BDD_PASSWORD=BrVcGbF0z7KNXLMENgzEq11ZP;
export GLOBAL_BDD_PASSWORD;


